export const ARAMEX_SUPPORTED_COUNTRIES = [
    { code: "AF", name: "Afghanistan" },
    { code: "AL", name: "Albania" },
    { code: "DZ", name: "Algeria" },
    { code: "AS", name: "American Samoa" },
    { code: "AD", name: "Andorra" },
    { code: "AO", name: "Angola" },
    { code: "AI", name: "Anguilla" },
    { code: "AG", name: "Antigua and Barbuda" },
    { code: "AR", name: "Argentina" },
    { code: "AM", name: "Armenia" },
    { code: "AW", name: "Aruba" },
    { code: "AU", name: "Australia" },
    { code: "AT", name: "Austria" },
    { code: "AZ", name: "Azerbaijan" },
    { code: "BS", name: "Bahamas" },
    { code: "BH", name: "Bahrain" },
    { code: "BD", name: "Bangladesh" },
    { code: "BB", name: "Barbados" },
    { code: "BY", name: "Belarus" },
    { code: "BE", name: "Belgium" },
    { code: "BZ", name: "Belize" },
    { code: "BJ", name: "Benin" },
    { code: "BM", name: "Bermuda" },
    { code: "BT", name: "Bhutan" },
    { code: "BO", name: "Bolivia" },
    { code: "BA", name: "Bosnia & Herzegovina" },
    { code: "BW", name: "Botswana" },
    { code: "IO", name: "British Indian Ocean Territory" },
    { code: "VG", name: "British Virgin Islands" },
    { code: "BR", name: "Brazil" },
    { code: "BN", name: "Brunei" },
    { code: "BG", name: "Bulgaria" },
    { code: "BF", name: "Burkina Faso" },
    { code: "BI", name: "Burundi" },
    { code: "KH", name: "Cambodia" },
    { code: "CM", name: "Cameroon" },
    { code: "CA", name: "Canada" },
    { code: "RY", name: "Canary Islands" },
    { code: "CV", name: "Cape Verde" },
    { code: "KY", name: "Cayman Islands" },
    { code: "CF", name: "Central African Republic" },
    { code: "TD", name: "Chad" },
    { code: "JE", name: "Channel Islands" },
    { code: "CL", name: "Chile" },
    { code: "CN", name: "China" },
    { code: "CX", name: "Christmas Island" },
    { code: "CC", name: "Cocos (Keeling) Islands" },
    { code: "CO", name: "Colombia" },
    { code: "KM", name: "Comoros" },
    { code: "CG", name: "Congo" },
    { code: "CK", name: "Cook Islands" },
    { code: "CR", name: "Costa Rica" },
    { code: "HR", name: "Croatia" },
    { code: "CU", name: "Cuba" },
    { code: "CY", name: "Cyprus" },
    { code: "CZ", name: "Czech Republic" },
    { code: "CD", name: "Democratic Republic of the Congo" },
    { code: "DK", name: "Denmark" },
    { code: "DJ", name: "Djibouti" },
    { code: "DM", name: "Dominica" },
    { code: "DO", name: "Dominican Republic" },
    { code: "TP", name: "East Timor" },
    { code: "EC", name: "Ecuador" },
    { code: "EG", name: "Egypt" },
    { code: "SV", name: "El Salvador" },
    { code: "GQ", name: "Equatorial Guinea" },
    { code: "ER", name: "Eritrea" },
    { code: "EE", name: "Estonia" },
    { code: "ET", name: "Ethiopia" },
    { code: "FK", name: "Falkland Islands" },
    { code: "FO", name: "Faroe Islands" },
    { code: "FJ", name: "Fiji" },
    { code: "FI", name: "Finland" },
    { code: "FR", name: "France" },
    { code: "GF", name: "French Guiana" },
    { code: "PF", name: "French Polynesia" },
    { code: "GA", name: "Gabon" },
    { code: "GM", name: "Gambia" },
    { code: "GE", name: "Georgia" },
    { code: "DE", name: "Germany" },
    { code: "GH", name: "Ghana" },
    { code: "GI", name: "Gibraltar" },
    { code: "GR", name: "Greece" },
    { code: "GL", name: "Greenland" },
    { code: "GD", name: "Grenada" },
    { code: "GP", name: "Guadeloupe" },
    { code: "GU", name: "Guam" },
    { code: "GT", name: "Guatemala" },
    { code: "GN", name: "Guinea" },
    { code: "GW", name: "Guinea-Bissau" },
    { code: "GY", name: "Guyana" },
    { code: "HT", name: "Haiti" },
    { code: "HM", name: "Heard & McDonald Islands" },
    { code: "HN", name: "Honduras" },
    { code: "HK", name: "Hong Kong" },
    { code: "HU", name: "Hungary" },
    { code: "IS", name: "Iceland" },
    { code: "IN", name: "India" },
    { code: "ID", name: "Indonesia" },
    { code: "IR", name: "Iran" },
    { code: "IQ", name: "Iraq" },
    { code: "IE", name: "Ireland" },
    { code: "IM", name: "Isle of Man" },
    { code: "IL", name: "Israel" },
    { code: "IT", name: "Italy" },
    { code: "CI", name: "Ivory Coast" },
    { code: "JM", name: "Jamaica" },
    { code: "JP", name: "Japan" },
    { code: "JO", name: "Jordan" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "KE", name: "Kenya" },
    { code: "KI", name: "Kiribati" },
    { code: "KP", name: "Korea, North" },
    { code: "KR", name: "Korea, South" },
    { code: "KW", name: "Kuwait" },
    { code: "KG", name: "Kyrgyzstan" },
    { code: "LA", name: "Laos" },
    { code: "LV", name: "Latvia" },
    { code: "LB", name: "Lebanon" },
    { code: "LS", name: "Lesotho" },
    { code: "LR", name: "Liberia" },
    { code: "LY", name: "Libya" },
    { code: "LI", name: "Liechtenstein" },
    { code: "LT", name: "Lithuania" },
    { code: "LU", name: "Luxembourg" },
    { code: "MO", name: "Macau" },
    { code: "MK", name: "Macedonia" },
    { code: "MG", name: "Madagascar" },
    { code: "MW", name: "Malawi" },
    { code: "MY", name: "Malaysia" },
    { code: "MV", name: "Maldives" },
    { code: "ML", name: "Mali" },
    { code: "MT", name: "Malta" },
    { code: "MH", name: "Marshall Islands" },
    { code: "MQ", name: "Martinique" },
    { code: "MR", name: "Mauritania" },
    { code: "MU", name: "Mauritius" },
    { code: "YT", name: "Mayotte" },
    { code: "MX", name: "Mexico" },
    { code: "FM", name: "Micronesia" },
    { code: "MD", name: "Moldova" },
    { code: "MC", name: "Monaco" },
    { code: "MN", name: "Mongolia" },
    { code: "MS", name: "Montserrat" },
    { code: "MA", name: "Morocco" },
    { code: "MZ", name: "Mozambique" },
    { code: "MM", name: "Myanmar" },
    { code: "NA", name: "Namibia" },
    { code: "NR", name: "Nauru" },
    { code: "NP", name: "Nepal" },
    { code: "NL", name: "Netherlands" },
    { code: "AN", name: "Netherlands Antilles" },
    { code: "NC", name: "New Caledonia" },
    { code: "NZ", name: "New Zealand" },
    { code: "NI", name: "Nicaragua" },
    { code: "NE", name: "Niger" },
    { code: "NG", name: "Nigeria" },
    { code: "NU", name: "Niue" },
    { code: "NF", name: "Norfolk Island" },
    { code: "MP", name: "Northern Mariana Islands" },
    { code: "NO", name: "Norway" },
    { code: "OM", name: "Oman" },
    { code: "PK", name: "Pakistan" },
    { code: "PW", name: "Palau" },
    { code: "PS", name: "Palestine" },
    { code: "PA", name: "Panama" },
    { code: "PG", name: "Papua New Guinea" },
    { code: "PY", name: "Paraguay" },
    { code: "PE", name: "Peru" },
    { code: "PH", name: "Philippines" },
    { code: "PN", name: "Pitcairn Islands" },
    { code: "PL", name: "Poland" },
    { code: "PT", name: "Portugal" },
    { code: "PR", name: "Puerto Rico" },
    { code: "QA", name: "Qatar" },
    { code: "RE", name: "Reunion Island" },
    { code: "RO", name: "Romania" },
    { code: "RU", name: "Russia" },
    { code: "RW", name: "Rwanda" },
    { code: "WS", name: "Samoa" },
    { code: "SM", name: "San Marino" },
    { code: "ST", name: "Sao Tome & Principe" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "SN", name: "Senegal" },
    { code: "YU", name: "Serbia & Montenegro" },
    { code: "SC", name: "Seychelles" },
    { code: "SL", name: "Sierra Leone" },
    { code: "SG", name: "Singapore" },
    { code: "SK", name: "Slovakia" },
    { code: "SI", name: "Slovenia" },
    { code: "SB", name: "Solomon Islands" },
    { code: "SO", name: "Somalia" },
    { code: "ZA", name: "South Africa" },
    { code: "ES", name: "Spain" },
    { code: "LK", name: "Sri Lanka" },
    { code: "HL", name: "St. Helena" },
    { code: "KN", name: "St. Kitts & Nevis" },
    { code: "LC", name: "St. Lucia" },
    { code: "PM", name: "St. Pierre & Miquelon" },
    { code: "VC", name: "St. Vincent & Grenadines" },
    { code: "SD", name: "Sudan" },
    { code: "SR", name: "Suriname" },
    { code: "SJ", name: "Svalbard & Jan Mayen" },
    { code: "SZ", name: "Swaziland" },
    { code: "SE", name: "Sweden" },
    { code: "CH", name: "Switzerland" },
    { code: "SY", name: "Syria" },
    { code: "TW", name: "Taiwan" },
    { code: "TJ", name: "Tajikistan" },
    { code: "TZ", name: "Tanzania" },
    { code: "TH", name: "Thailand" },
    { code: "TL", name: "Timor-Leste" },
    { code: "TG", name: "Togo" },
    { code: "TK", name: "Tokelau" },
    { code: "TO", name: "Tonga" },
    { code: "TT", name: "Trinidad & Tobago" },
    { code: "TN", name: "Tunisia" },
    { code: "TR", name: "Turkey" },
    { code: "TM", name: "Turkmenistan" },
    { code: "TC", name: "Turks & Caicos Islands" },
    { code: "TV", name: "Tuvalu" },
    { code: "UG", name: "Uganda" },
    { code: "UA", name: "Ukraine" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "GB", name: "United Kingdom" },
    { code: "US", name: "United States" },
    { code: "UM", name: "US Minor Outlying Islands" },
    { code: "VI", name: "US Virgin Islands" },
    { code: "UY", name: "Uruguay" },
    { code: "UZ", name: "Uzbekistan" },
    { code: "VU", name: "Vanuatu" },
    { code: "VA", name: "Vatican City" },
    { code: "VE", name: "Venezuela" },
    { code: "VN", name: "Vietnam" },
    { code: "WF", name: "Wallis & Futuna Islands" },
    { code: "EH", name: "Western Sahara" },
    { code: "YE", name: "Yemen" },
    { code: "ZM", name: "Zambia" },
    { code: "ZW", name: "Zimbabwe" }
];

export const ARAMEX_SUPPORTED_CURRENCIES = [
    { code: "AED", name: "Dirham (AED)" },
    { code: "AFA", name: "Afghani (AFA)" },
    { code: "ALL", name: "Lek (ALL)" },
    { code: "AMD", name: "Dram (AMD)" },
    { code: "ANG", name: "Antillean Guilder (ANG)" },
    { code: "AOK", name: "Kwanza (AOK)" },
    { code: "ARS", name: "Argentine Peso (ARS)" },
    { code: "AUD", name: "Australian Dollar (AUD)" },
    { code: "AWG", name: "Aruban Florin (AWG)" },
    { code: "BAD", name: "Bosnian Dinar (BAD)" },
    { code: "BBD", name: "Barbadian Dollar (BBD)" },
    { code: "BGL", name: "Lev (BGL)" },
    { code: "BHD", name: "Bahraini Dinar (BHD)" },
    { code: "BIF", name: "Burundi Franc (BIF)" },
    { code: "BMD", name: "Bermudian Dollar (BMD)" },
    { code: "BND", name: "Bruneian Dollar (BND)" },
    { code: "BOB", name: "Boliviano (BOB)" },
    { code: "BRE", name: "Cruzeiro (BRE)" },
    { code: "BTN", name: "Ngultrum (BTN)" },
    { code: "BWP", name: "Pula (BWP)" },
    { code: "BZD", name: "Belizean Dollar (BZD)" },
    { code: "CAD", name: "Canadian Dollar (CAD)" },
    { code: "CHF", name: "Swiss Franc (CHF)" },
    { code: "CID", name: "Caymanian Dollar (CID)" },
    { code: "CLP", name: "Chilean Peso (CLP)" },
    { code: "CNY", name: "Yuan (CNY)" },
    { code: "COP", name: "Colombian Peso (COP)" },
    { code: "CRC", name: "Costa Rican Colon (CRC)" },
    { code: "CUP", name: "Cuban Peso (CUP)" },
    { code: "CVE", name: "Cape Verdean Escudo (CVE)" },
    { code: "CYP", name: "Cypriot Pound (CYP)" },
    { code: "CZK", name: "Koruna (CZK)" },
    { code: "DJF", name: "Djibouti Franc (DJF)" },
    { code: "DKK", name: "Danish Krone (DKK)" },
    { code: "DOP", name: "Dominican Peso (DOP)" },
    { code: "DZD", name: "Algerian Dinar (DZD)" },
    { code: "ECS", name: "Sucre (ECS)" },
    { code: "EEK", name: "Kroon (EEK)" },
    { code: "EGP", name: "Egyptian Pound (EGP)" },
    { code: "ERB", name: "Birr (ERB)" },
    { code: "ETB", name: "Birr (ETB)" },
    { code: "EUR", name: "Euro (EUR)" },
    { code: "FJD", name: "Fijian Dollar (FJD)" },
    { code: "FKP", name: "Falkland Pound (FKP)" },
    { code: "FRF", name: "French Franc (FRF)" },
    { code: "GBP", name: "British Pound (GBP)" },
    { code: "GEK", name: "Lari (GEK)" },
    { code: "GHC", name: "Cedi (GHC)" },
    { code: "GIP", name: "Gibraltar Pound (GIP)" },
    { code: "GMD", name: "Dalasi (GMD)" },
    { code: "GNS", name: "Syli (GNS)" },
    { code: "GTQ", name: "Quetzal (GTQ)" },
    { code: "GWP", name: "Guinea-Bissauan Peso (GWP)" },
    { code: "GYD", name: "Guyanese Dollar (GYD)" },
    { code: "HKD", name: "Hong Kong Dollar (HKD)" },
    { code: "HNL", name: "Lempira (HNL)" },
    { code: "HRK", name: "Kuna (HRK)" },
    { code: "HTG", name: "Gourde (HTG)" },
    { code: "HUF", name: "Forint (HUF)" },
    { code: "IDR", name: "Indonesian Rupiah (IDR)" },
    { code: "ILS", name: "New Israeli Shekel (ILS)" },
    { code: "INR", name: "Indian Rupee (INR)" },
    { code: "IQD", name: "Iraqi Dinar (IQD)" },
    { code: "IRR", name: "Iranian Rial (IRR)" },
    { code: "ISK", name: "Krona (ISK)" },
    { code: "ITL", name: "Italian Lira (ITL)" },
    { code: "JMD", name: "Jamaican Dollar (JMD)" },
    { code: "JOD", name: "Jordanian Dinar (JOD)" },
    { code: "JPY", name: "Yen (JPY)" },
    { code: "KES", name: "Kenyan Shilling (KES)" },
    { code: "KGS", name: "Som (KGS)" },
    { code: "KHR", name: "Riel (KHR)" },
    { code: "KMF", name: "Comoran Franc (KMF)" },
    { code: "KPW", name: "Won (KPW)" },
    { code: "KRW", name: "Won (KRW)" },
    { code: "KWD", name: "Kuwaiti Dinar (KWD)" },
    { code: "KZT", name: "Tenge (KZT)" },
    { code: "LAK", name: "New Kip (LAK)" },
    { code: "LBP", name: "Lebanese Pound (LBP)" },
    { code: "LKR", name: "Sri Lankan Rupee (LKR)" },
    { code: "LRD", name: "Liberian Dollar (LRD)" },
    { code: "LSL", name: "Loti (LSL)" },
    { code: "LTL", name: "Litas (LTL)" },
    { code: "LVL", name: "Lat (LVL)" },
    { code: "LYD", name: "Libyan Dinar (LYD)" },
    { code: "MAD", name: "Moroccan Dirham (MAD)" },
    { code: "MDL", name: "Leu (MDL)" },
    { code: "MGF", name: "Ariary (MGF)" },
    { code: "MKD", name: "Denar (MKD)" },
    { code: "MLF", name: "C.F.A. Franc (MLF)" },
    { code: "MMK", name: "Kyat (MMK)" },
    { code: "MNT", name: "Tughrik (MNT)" },
    { code: "MOP", name: "Pataca (MOP)" },
    { code: "MRO", name: "Ouguiya (MRO)" },
    { code: "MTL", name: "Maltese Lira (MTL)" },
    { code: "MUR", name: "Mauritian Rupee (MUR)" },
    { code: "MVR", name: "Rufiyaa (MVR)" },
    { code: "MWK", name: "Malawian Kwacha (MWK)" },
    { code: "MXN", name: "Nuevo Peso (MXN)" },
    { code: "MYR", name: "Ringgit (MYR)" },
    { code: "MZM", name: "Metical (MZM)" },
    { code: "NAD", name: "Namibian Dollar (NAD)" },
    { code: "NGN", name: "Naira (NGN)" },
    { code: "NIC", name: "Gold Cordoba (NIC)" },
    { code: "NOK", name: "Norwegian Krone (NOK)" },
    { code: "NPR", name: "Nepalese Rupee (NPR)" },
    { code: "NZD", name: "New Zealand Dollar (NZD)" },
    { code: "OMR", name: "Omani Rial (OMR)" },
    { code: "PAB", name: "Balboa (PAB)" },
    { code: "PEN", name: "Nuevo Sol (PEN)" },
    { code: "PGK", name: "Kina (PGK)" },
    { code: "PHP", name: "Philippine Peso (PHP)" },
    { code: "PKR", name: "Pakistani Rupee (PKR)" },
    { code: "PLZ", name: "New Zloty (PLZ)" },
    { code: "PYG", name: "Guarani (PYG)" },
    { code: "QAR", name: "Qatari Riyal (QAR)" },
    { code: "ROL", name: "Leu (ROL)" },
    { code: "RUR", name: "Ruble (RUR)" },
    { code: "RWF", name: "Rwandan Franc (RWF)" },
    { code: "SAR", name: "Saudi Riyal (SAR)" },
    { code: "SAT", name: "Tala (SAT)" },
    { code: "SBD", name: "Solomon Islands Dollar (SBD)" },
    { code: "SCR", name: "Seychelles Rupee (SCR)" },
    { code: "SDD", name: "Sudanese Dinar (SDD)" },
    { code: "SEK", name: "Swedish Krona (SEK)" },
    { code: "SGD", name: "Singapore Dollar (SGD)" },
    { code: "SHP", name: "Pound (SHP)" },
    { code: "SIT", name: "Tolar (SIT)" },
    { code: "SKK", name: "Koruna (SKK)" },
    { code: "SLL", name: "Leone (SLL)" },
    { code: "SOS", name: "Somali Shilling (SOS)" },
    { code: "SPP", name: "Spanish Peseta (SPP)" },
    { code: "SRG", name: "Surinamese Guilder (SRG)" },
    { code: "STD", name: "Dobra (STD)" },
    { code: "SVC", name: "Salvadoran Colon (SVC)" },
    { code: "SYP", name: "Syrian Pound (SYP)" },
    { code: "SZL", name: "Lilangeni (SZL)" },
    { code: "TMM", name: "Manat (TMM)" },
    { code: "TND", name: "Tunisian Dinar (TND)" },
    { code: "TOP", name: "Pa'anga (TOP)" },
    { code: "TTD", name: "Trinidad & Tobago Dollar (TTD)" },
    { code: "TWD", name: "New Taiwan Dollar (TWD)" },
    { code: "TZS", name: "Tanzanian Shilling (TZS)" },
    { code: "UAH", name: "Hryvnia (UAH)" },
    { code: "UGX", name: "Ugandan Shilling (UGX)" },
    { code: "USD", name: "United States Dollar (USD)" },
    { code: "UYP", name: "New Uruguayan Peso (UYP)" },
    { code: "VEB", name: "Bolivar (VEB)" },
    { code: "VND", name: "New Dong (VND)" },
    { code: "VUV", name: "Vatu (VUV)" },
    { code: "XAF", name: "C.F.A. Franc (XAF)" },
    { code: "XCD", name: "East Caribbean Dollar (XCD)" },
    { code: "XOF", name: "C.F.A. Franc (XOF)" },
    { code: "XPF", name: "C.F.A. Franc (XPF)" },
    { code: "YER", name: "North Yemeni Riyal (YER)" },
    { code: "YTL", name: "Turkish Lira (YTL)" },
    { code: "YUN", name: "New Dinar (YUN)" },
    { code: "ZAR", name: "Rand (ZAR)" },
    { code: "ZMK", name: "Zambian Kwacha (ZMK)" },
    { code: "ZRN", name: "New Zaire (ZRN)" },
    { code: "ZWD", name: "Zimbabwean Dollar (ZWD)" }
];

export const ARAMEX_PRODUCT_CONFIG = {
    DOM: {
        label: "Domestic (DOM)",
        types: [
            { code: "ONP", name: "Overnight Parcel (Boxes, Goods)", isDutiable: false },
            { code: "OND", name: "Overnight Document (Letters, Papers)", isDutiable: false }
        ]
    },
    EXP: {
        label: "International Express (EXP)",
        types: [
            { code: "PPX", name: "Priority Parcel Express (Goods/Merchandise)", isDutiable: true },
            { code: "PDX", name: "Priority Document Express (Legal, Docs)", isDutiable: false },
            { code: "EPX", name: "Economy Parcel Express (Cross-border E-com)", isDutiable: true },
            { code: "PLX", name: "Priority Letter Express (< 0.5kg)", isDutiable: false },
            { code: "DPX", name: "Deferred Parcel Express (2nd Day Delivery)", isDutiable: true },
            { code: "DDX", name: "Deferred Document Express (2nd Day Docs)", isDutiable: false },
            { code: "GPX", name: "Ground Parcel Express (Road Feeder)", isDutiable: true },
            { code: "GDX", name: "Ground Document Express (Road Feeder)", isDutiable: false }
        ]
    }
};

export const VALID_ARAMEX_COUNTRY_CODES = new Set(
    ARAMEX_SUPPORTED_COUNTRIES.map((c) => c.code)
);