export const ARAMEX_SUPPORTED_COUNTRIES = [
    { label: "Afghanistan", value: "AF" },
    { label: "Albania", value: "AL" },
    { label: "Algeria", value: "DZ" },
    { label: "American Samoa", value: "AS" },
    { label: "Andorra", value: "AD" },
    { label: "Angola", value: "AO" },
    { label: "Anguilla", value: "AI" },
    { label: "Antigua and Barbuda", value: "AG" },
    { label: "Argentina", value: "AR" },
    { label: "Armenia", value: "AM" },
    { label: "Aruba", value: "AW" },
    { label: "Australia", value: "AU" },
    { label: "Austria", value: "AT" },
    { label: "Azerbaijan", value: "AZ" },
    { label: "Bahamas", value: "BS" },
    { label: "Bahrain", value: "BH" },
    { label: "Bangladesh", value: "BD" },
    { label: "Barbados", value: "BB" },
    { label: "Belarus", value: "BY" },
    { label: "Belgium", value: "BE" },
    { label: "Belize", value: "BZ" },
    { label: "Benin", value: "BJ" },
    { label: "Bermuda", value: "BM" },
    { label: "Bhutan", value: "BT" },
    { label: "Bolivia", value: "BO" },
    { label: "Bosnia & Herzegovina", value: "BA" },
    { label: "Botswana", value: "BW" },
    { label: "British Indian Ocean Territory", value: "IO" },
    { label: "British Virgin Islands", value: "VG" },
    { label: "Brazil", value: "BR" },
    { label: "Brunei", value: "BN" },
    { label: "Bulgaria", value: "BG" },
    { label: "Burkina Faso", value: "BF" },
    { label: "Burundi", value: "BI" },
    { label: "Cambodia", value: "KH" },
    { label: "Cameroon", value: "CM" },
    { label: "Canada", value: "CA" },
    { label: "Canary Islands", value: "RY" },
    { label: "Cape Verde", value: "CV" },
    { label: "Cayman Islands", value: "KY" },
    { label: "Central African Republic", value: "CF" },
    { label: "Chad", value: "TD" },
    { label: "Channel Islands", value: "JE" },
    { label: "Chile", value: "CL" },
    { label: "China", value: "CN" },
    { label: "Christmas Island", value: "CX" },
    { label: "Cocos (Keeling) Islands", value: "CC" },
    { label: "Colombia", value: "CO" },
    { label: "Comoros", value: "KM" },
    { label: "Congo", value: "CG" },
    { label: "Cook Islands", value: "CK" },
    { label: "Costa Rica", value: "CR" },
    { label: "Croatia", value: "HR" },
    { label: "Cuba", value: "CU" },
    { label: "Cyprus", value: "CY" },
    { label: "Czech Republic", value: "CZ" },
    { label: "Democratic Republic of the Congo", value: "CD" },
    { label: "Denmark", value: "DK" },
    { label: "Djibouti", value: "DJ" },
    { label: "Dominica", value: "DM" },
    { label: "Dominican Republic", value: "DO" },
    { label: "East Timor", value: "TP" },
    { label: "Ecuador", value: "EC" },
    { label: "Egypt", value: "EG" },
    { label: "El Salvador", value: "SV" },
    { label: "Equatorial Guinea", value: "GQ" },
    { label: "Eritrea", value: "ER" },
    { label: "Estonia", value: "EE" },
    { label: "Ethiopia", value: "ET" },
    { label: "Falkland Islands", value: "FK" },
    { label: "Faroe Islands", value: "FO" },
    { label: "Fiji", value: "FJ" },
    { label: "Finland", value: "FI" },
    { label: "France", value: "FR" },
    { label: "French Guiana", value: "GF" },
    { label: "French Polynesia", value: "PF" },
    { label: "Gabon", value: "GA" },
    { label: "Gambia", value: "GM" },
    { label: "Georgia", value: "GE" },
    { label: "Germany", value: "DE" },
    { label: "Ghana", value: "GH" },
    { label: "Gibraltar", value: "GI" },
    { label: "Greece", value: "GR" },
    { label: "Greenland", value: "GL" },
    { label: "Grenada", value: "GD" },
    { label: "Guadeloupe", value: "GP" },
    { label: "Guam", value: "GU" },
    { label: "Guatemala", value: "GT" },
    { label: "Guinea", value: "GN" },
    { label: "Guinea-Bissau", value: "GW" },
    { label: "Guyana", value: "GY" },
    { label: "Haiti", value: "HT" },
    { label: "Heard & McDonald Islands", value: "HM" },
    { label: "Honduras", value: "HN" },
    { label: "Hong Kong", value: "HK" },
    { label: "Hungary", value: "HU" },
    { label: "Iceland", value: "IS" },
    { label: "India", value: "IN" },
    { label: "Indonesia", value: "ID" },
    { label: "Iran", value: "IR" },
    { label: "Iraq", value: "IQ" },
    { label: "Ireland", value: "IE" },
    { label: "Isle of Man", value: "IM" },
    { label: "Israel", value: "IL" },
    { label: "Italy", value: "IT" },
    { label: "Ivory Coast", value: "CI" },
    { label: "Jamaica", value: "JM" },
    { label: "Japan", value: "JP" },
    { label: "Jordan", value: "JO" },
    { label: "Kazakhstan", value: "KZ" },
    { label: "Kenya", value: "KE" },
    { label: "Kiribati", value: "KI" },
    { label: "Korea, North", value: "KP" },
    { label: "Korea, South", value: "KR" },
    { label: "Kuwait", value: "KW" },
    { label: "Kyrgyzstan", value: "KG" },
    { label: "Laos", value: "LA" },
    { label: "Latvia", value: "LV" },
    { label: "Lebanon", value: "LB" },
    { label: "Lesotho", value: "LS" },
    { label: "Liberia", value: "LR" },
    { label: "Libya", value: "LY" },
    { label: "Liechtenstein", value: "LI" },
    { label: "Lithuania", value: "LT" },
    { label: "Luxembourg", value: "LU" },
    { label: "Macau", value: "MO" },
    { label: "Macedonia", value: "MK" },
    { label: "Madagascar", value: "MG" },
    { label: "Malawi", value: "MW" },
    { label: "Malaysia", value: "MY" },
    { label: "Maldives", value: "MV" },
    { label: "Mali", value: "ML" },
    { label: "Malta", value: "MT" },
    { label: "Marshall Islands", value: "MH" },
    { label: "Martinique", value: "MQ" },
    { label: "Mauritania", value: "MR" },
    { label: "Mauritius", value: "MU" },
    { label: "Mayotte", value: "YT" },
    { label: "Mexico", value: "MX" },
    { label: "Micronesia", value: "FM" },
    { label: "Moldova", value: "MD" },
    { label: "Monaco", value: "MC" },
    { label: "Mongolia", value: "MN" },
    { label: "Montserrat", value: "MS" },
    { label: "Morocco", value: "MA" },
    { label: "Mozambique", value: "MZ" },
    { label: "Myanmar", value: "MM" },
    { label: "Namibia", value: "NA" },
    { label: "Nauru", value: "NR" },
    { label: "Nepal", value: "NP" },
    { label: "Netherlands", value: "NL" },
    { label: "Netherlands Antilles", value: "AN" },
    { label: "New Caledonia", value: "NC" },
    { label: "New Zealand", value: "NZ" },
    { label: "Nicaragua", value: "NI" },
    { label: "Niger", value: "NE" },
    { label: "Nigeria", value: "NG" },
    { label: "Niue", value: "NU" },
    { label: "Norfolk Island", value: "NF" },
    { label: "Northern Mariana Islands", value: "MP" },
    { label: "Norway", value: "NO" },
    { label: "Oman", value: "OM" },
    { label: "Pakistan", value: "PK" },
    { label: "Palau", value: "PW" },
    { label: "Palestine", value: "PS" },
    { label: "Panama", value: "PA" },
    { label: "Papua New Guinea", value: "PG" },
    { label: "Paraguay", value: "PY" },
    { label: "Peru", value: "PE" },
    { label: "Philippines", value: "PH" },
    { label: "Pitcairn Islands", value: "PN" },
    { label: "Poland", value: "PL" },
    { label: "Portugal", value: "PT" },
    { label: "Puerto Rico", value: "PR" },
    { label: "Qatar", value: "QA" },
    { label: "Reunion Island", value: "RE" },
    { label: "Romania", value: "RO" },
    { label: "Russia", value: "RU" },
    { label: "Rwanda", value: "RW" },
    { label: "Samoa", value: "WS" },
    { label: "San Marino", value: "SM" },
    { label: "Sao Tome & Principe", value: "ST" },
    { label: "Saudi Arabia", value: "SA" },
    { label: "Senegal", value: "SN" },
    { label: "Serbia & Montenegro", value: "YU" },
    { label: "Seychelles", value: "SC" },
    { label: "Sierra Leone", value: "SL" },
    { label: "Singapore", value: "SG" },
    { label: "Slovakia", value: "SK" },
    { label: "Slovenia", value: "SI" },
    { label: "Solomon Islands", value: "SB" },
    { label: "Somalia", value: "SO" },
    { label: "South Africa", value: "ZA" },
    { label: "Spain", value: "ES" },
    { label: "Sri Lanka", value: "LK" },
    { label: "St. Helena", value: "HL" },
    { label: "St. Kitts & Nevis", value: "KN" },
    { label: "St. Lucia", value: "LC" },
    { label: "St. Pierre & Miquelon", value: "PM" },
    { label: "St. Vincent & Grenadines", value: "VC" },
    { label: "Sudan", value: "SD" },
    { label: "Suriname", value: "SR" },
    { label: "Svalbard & Jan Mayen", value: "SJ" },
    { label: "Swaziland", value: "SZ" },
    { label: "Sweden", value: "SE" },
    { label: "Switzerland", value: "CH" },
    { label: "Syria", value: "SY" },
    { label: "Taiwan", value: "TW" },
    { label: "Tajikistan", value: "TJ" },
    { label: "Tanzania", value: "TZ" },
    { label: "Thailand", value: "TH" },
    { label: "Timor-Leste", value: "TL" },
    { label: "Togo", value: "TG" },
    { label: "Tokelau", value: "TK" },
    { label: "Tonga", value: "TO" },
    { label: "Trinidad & Tobago", value: "TT" },
    { label: "Tunisia", value: "TN" },
    { label: "Turkey", value: "TR" },
    { label: "Turkmenistan", value: "TM" },
    { label: "Turks & Caicos Islands", value: "TC" },
    { label: "Tuvalu", value: "TV" },
    { label: "Uganda", value: "UG" },
    { label: "Ukraine", value: "UA" },
    { label: "United Arab Emirates", value: "AE" },
    { label: "United Kingdom", value: "GB" },
    { label: "United States", value: "US" },
    { label: "US Minor Outlying Islands", value: "UM" },
    { label: "US Virgin Islands", value: "VI" },
    { label: "Uruguay", value: "UY" },
    { label: "Uzbekistan", value: "UZ" },
    { label: "Vanuatu", value: "VU" },
    { label: "Vatican City", value: "VA" },
    { label: "Venezuela", value: "VE" },
    { label: "Vietnam", value: "VN" },
    { label: "Wallis & Futuna Islands", value: "WF" },
    { label: "Western Sahara", value: "EH" },
    { label: "Yemen", value: "YE" },
    { label: "Zambia", value: "ZM" },
    { label: "Zimbabwe", value: "ZW" }
];

export const ARAMEX_SUPPORTED_CURRENCIES = [
    { label: "Dirham (AED)", value: "AED" },
    { label: "Afghani (AFA)", value: "AFA" },
    { label: "Lek (ALL)", value: "ALL" },
    { label: "Dram (AMD)", value: "AMD" },
    { label: "Antillean Guilder (ANG)", value: "ANG" },
    { label: "Kwanza (AOK)", value: "AOK" },
    { label: "Argentine Peso (ARS)", value: "ARS" },
    { label: "Australian Dollar (AUD)", value: "AUD" },
    { label: "Aruban Florin (AWG)", value: "AWG" },
    { label: "Bosnian Dinar (BAD)", value: "BAD" },
    { label: "Barbadian Dollar (BBD)", value: "BBD" },
    { label: "Lev (BGL)", value: "BGL" },
    { label: "Bahraini Dinar (BHD)", value: "BHD" },
    { label: "Burundi Franc (BIF)", value: "BIF" },
    { label: "Bermudian Dollar (BMD)", value: "BMD" },
    { label: "Bruneian Dollar (BND)", value: "BND" },
    { label: "Boliviano (BOB)", value: "BOB" },
    { label: "Cruzeiro (BRE)", value: "BRE" },
    { label: "Ngultrum (BTN)", value: "BTN" },
    { label: "Pula (BWP)", value: "BWP" },
    { label: "Belizean Dollar (BZD)", value: "BZD" },
    { label: "Canadian Dollar (CAD)", value: "CAD" },
    { label: "Swiss Franc (CHF)", value: "CHF" },
    { label: "Caymanian Dollar (CID)", value: "CID" },
    { label: "Chilean Peso (CLP)", value: "CLP" },
    { label: "Yuan (CNY)", value: "CNY" },
    { label: "Colombian Peso (COP)", value: "COP" },
    { label: "Costa Rican Colon (CRC)", value: "CRC" },
    { label: "Cuban Peso (CUP)", value: "CUP" },
    { label: "Cape Verdean Escudo (CVE)", value: "CVE" },
    { label: "Cypriot Pound (CYP)", value: "CYP" },
    { label: "Koruna (CZK)", value: "CZK" },
    { label: "Djibouti Franc (DJF)", value: "DJF" },
    { label: "Danish Krone (DKK)", value: "DKK" },
    { label: "Dominican Peso (DOP)", value: "DOP" },
    { label: "Algerian Dinar (DZD)", value: "DZD" },
    { label: "Sucre (ECS)", value: "ECS" },
    { label: "Kroon (EEK)", value: "EEK" },
    { label: "Egyptian Pound (EGP)", value: "EGP" },
    { label: "Birr (ERB)", value: "ERB" },
    { label: "Birr (ETB)", value: "ETB" },
    { label: "Euro (EUR)", value: "EUR" },
    { label: "Fijian Dollar (FJD)", value: "FJD" },
    { label: "Falkland Pound (FKP)", value: "FKP" },
    { label: "French Franc (FRF)", value: "FRF" },
    { label: "British Pound (GBP)", value: "GBP" },
    { label: "Lari (GEK)", value: "GEK" },
    { label: "Cedi (GHC)", value: "GHC" },
    { label: "Gibraltar Pound (GIP)", value: "GIP" },
    { label: "Dalasi (GMD)", value: "GMD" },
    { label: "Syli (GNS)", value: "GNS" },
    { label: "Quetzal (GTQ)", value: "GTQ" },
    { label: "Guinea-Bissauan Peso (GWP)", value: "GWP" },
    { label: "Guyanese Dollar (GYD)", value: "GYD" },
    { label: "Hong Kong Dollar (HKD)", value: "HKD" },
    { label: "Lempira (HNL)", value: "HNL" },
    { label: "Kuna (HRK)", value: "HRK" },
    { label: "Gourde (HTG)", value: "HTG" },
    { label: "Forint (HUF)", value: "HUF" },
    { label: "Indonesian Rupiah (IDR)", value: "IDR" },
    { label: "New Israeli Shekel (ILS)", value: "ILS" },
    { label: "Indian Rupee (INR)", value: "INR" },
    { label: "Iraqi Dinar (IQD)", value: "IQD" },
    { label: "Iranian Rial (IRR)", value: "IRR" },
    { label: "Krona (ISK)", value: "ISK" },
    { label: "Italian Lira (ITL)", value: "ITL" },
    { label: "Jamaican Dollar (JMD)", value: "JMD" },
    { label: "Jordanian Dinar (JOD)", value: "JOD" },
    { label: "Yen (JPY)", value: "JPY" },
    { label: "Kenyan Shilling (KES)", value: "KES" },
    { label: "Som (KGS)", value: "KGS" },
    { label: "Riel (KHR)", value: "KHR" },
    { label: "Comoran Franc (KMF)", value: "KMF" },
    { label: "Won (KPW)", value: "KPW" },
    { label: "Won (KRW)", value: "KRW" },
    { label: "Kuwaiti Dinar (KWD)", value: "KWD" },
    { label: "Tenge (KZT)", value: "KZT" },
    { label: "New Kip (LAK)", value: "LAK" },
    { label: "Lebanese Pound (LBP)", value: "LBP" },
    { label: "Sri Lankan Rupee (LKR)", value: "LKR" },
    { label: "Liberian Dollar (LRD)", value: "LRD" },
    { label: "Loti (LSL)", value: "LSL" },
    { label: "Litas (LTL)", value: "LTL" },
    { label: "Lat (LVL)", value: "LVL" },
    { label: "Libyan Dinar (LYD)", value: "LYD" },
    { label: "Moroccan Dirham (MAD)", value: "MAD" },
    { label: "Leu (MDL)", value: "MDL" },
    { label: "Ariary (MGF)", value: "MGF" },
    { label: "Denar (MKD)", value: "MKD" },
    { label: "C.F.A. Franc (MLF)", value: "MLF" },
    { label: "Kyat (MMK)", value: "MMK" },
    { label: "Tughrik (MNT)", value: "MNT" },
    { label: "Pataca (MOP)", value: "MOP" },
    { label: "Ouguiya (MRO)", value: "MRO" },
    { label: "Maltese Lira (MTL)", value: "MTL" },
    { label: "Mauritian Rupee (MUR)", value: "MUR" },
    { label: "Rufiyaa (MVR)", value: "MVR" },
    { label: "Malawian Kwacha (MWK)", value: "MWK" },
    { label: "Nuevo Peso (MXN)", value: "MXN" },
    { label: "Ringgit (MYR)", value: "MYR" },
    { label: "Metical (MZM)", value: "MZM" },
    { label: "Namibian Dollar (NAD)", value: "NAD" },
    { label: "Naira (NGN)", value: "NGN" },
    { label: "Gold Cordoba (NIC)", value: "NIC" },
    { label: "Norwegian Krone (NOK)", value: "NOK" },
    { label: "Nepalese Rupee (NPR)", value: "NPR" },
    { label: "New Zealand Dollar (NZD)", value: "NZD" },
    { label: "Omani Rial (OMR)", value: "OMR" },
    { label: "Balboa (PAB)", value: "PAB" },
    { label: "Nuevo Sol (PEN)", value: "PEN" },
    { label: "Kina (PGK)", value: "PGK" },
    { label: "Philippine Peso (PHP)", value: "PHP" },
    { label: "Pakistani Rupee (PKR)", value: "PKR" },
    { label: "New Zloty (PLZ)", value: "PLZ" },
    { label: "Guarani (PYG)", value: "PYG" },
    { label: "Qatari Riyal (QAR)", value: "QAR" },
    { label: "Leu (ROL)", value: "ROL" },
    { label: "Ruble (RUR)", value: "RUR" },
    { label: "Rwandan Franc (RWF)", value: "RWF" },
    { label: "Saudi Riyal (SAR)", value: "SAR" },
    { label: "Tala (SAT)", value: "SAT" },
    { label: "Solomon Islands Dollar (SBD)", value: "SBD" },
    { label: "Seychelles Rupee (SCR)", value: "SCR" },
    { label: "Sudanese Dinar (SDD)", value: "SDD" },
    { label: "Swedish Krona (SEK)", value: "SEK" },
    { label: "Singapore Dollar (SGD)", value: "SGD" },
    { label: "Pound (SHP)", value: "SHP" },
    { label: "Tolar (SIT)", value: "SIT" },
    { label: "Koruna (SKK)", value: "SKK" },
    { label: "Leone (SLL)", value: "SLL" },
    { label: "Somali Shilling (SOS)", value: "SOS" },
    { label: "Spanish Peseta (SPP)", value: "SPP" },
    { label: "Surinamese Guilder (SRG)", value: "SRG" },
    { label: "Dobra (STD)", value: "STD" },
    { label: "Salvadoran Colon (SVC)", value: "SVC" },
    { label: "Syrian Pound (SYP)", value: "SYP" },
    { label: "Lilangeni (SZL)", value: "SZL" },
    { label: "Manat (TMM)", value: "TMM" },
    { label: "Tunisian Dinar (TND)", value: "TND" },
    { label: "Pa'anga (TOP)", value: "TOP" },
    { label: "Trinidad & Tobago Dollar (TTD)", value: "TTD" },
    { label: "New Taiwan Dollar (TWD)", value: "TWD" },
    { label: "Tanzanian Shilling (TZS)", value: "TZS" },
    { label: "Hryvnia (UAH)", value: "UAH" },
    { label: "Ugandan Shilling (UGX)", value: "UGX" },
    { label: "United States Dollar (USD)", value: "USD" },
    { label: "New Uruguayan Peso (UYP)", value: "UYP" },
    { label: "Bolivar (VEB)", value: "VEB" },
    { label: "New Dong (VND)", value: "VND" },
    { label: "Vatu (VUV)", value: "VUV" },
    { label: "C.F.A. Franc (XAF)", value: "XAF" },
    { label: "East Caribbean Dollar (XCD)", value: "XCD" },
    { label: "C.F.A. Franc (XOF)", value: "XOF" },
    { label: "C.F.A. Franc (XPF)", value: "XPF" },
    { label: "North Yemeni Riyal (YER)", value: "YER" },
    { label: "Turkish Lira (YTL)", value: "YTL" },
    { label: "New Dinar (YUN)", value: "YUN" },
    { label: "Rand (ZAR)", value: "ZAR" },
    { label: "Zambian Kwacha (ZMK)", value: "ZMK" },
    { label: "New Zaire (ZRN)", value: "ZRN" },
    { label: "Zimbabwean Dollar (ZWD)", value: "ZWD" }
];

export const ARAMEX_PRODUCT_CONFIG = {
    DOM: {
        label: "Domestic (DOM)",
        types: [
            { code: "ONP", name: "Overnight Parcel (Boxes, Goods)", isDutiable: false },
            { code: "OND", name: "Overnight Document (Letters, Papers)", isDutiable: false }
        ]
    },
    EXP: {
        label: "International Express (EXP)",
        types: [
            { code: "PPX", name: "Priority Parcel Express (Goods/Merchandise)", isDutiable: true },
            { code: "PDX", name: "Priority Document Express (Legal, Docs)", isDutiable: false },
            { code: "EPX", name: "Economy Parcel Express (Cross-border E-com)", isDutiable: true },
            { code: "PLX", name: "Priority Letter Express (< 0.5kg)", isDutiable: false },
            { code: "DPX", name: "Deferred Parcel Express (2nd Day Delivery)", isDutiable: true },
            { code: "DDX", name: "Deferred Document Express (2nd Day Docs)", isDutiable: false },
            { code: "GPX", name: "Ground Parcel Express (Road Feeder)", isDutiable: true },
            { code: "GDX", name: "Ground Document Express (Road Feeder)", isDutiable: false }
        ]
    }
};

export const VALID_ARAMEX_COUNTRY_CODES = new Set(
    ARAMEX_SUPPORTED_COUNTRIES.map((c) => c.value)
);